version: '3.9'

services:
  app_prod:
    container_name: nestTweetsProd
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/dist
    depends_on:
      - db_prod
  db_prod:
    image: mongo:6.0.2
    container_name: mongoTweetsProd
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo